server:
  port: 9090

spring:
  datasource:
    url : jdbc:oracle:thin:@180.97.80.177:1621:traveldb
    username : jike
    password : jike17712613261
    driverClassName : oracle.jdbc.OracleDriver

## Specify the DBMS
  jpa:
#    database : ORACLE
## Show or not log for each sql query
    show-sql : true
## Hibernate ddl auto (create, create-drop, update)
#    hibernate:
#      ddl-auto : update
## Naming strategy
##      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
#    open-in-view : false
## stripped before adding them to the entity manager)
##    properties:
##      hibernate:
##        dialect : org.hibernate.dialect.Oracle10gDialect

#security:
#  user:
#    name: admin
#    password: test

  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 180.97.80.177
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: tE2-WJZ-u5F-6UJ
    # 连接超时时间（毫秒）
    timeout: 0
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
